name: 'strawberry_bi'
version: '1.0.0'
config-version: 2

profile: 'strawberry_bi'

model-paths: ['models']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']
analysis-paths: ['analyses']

models:

  bronze:
    +schema: BRONZE
    +materialized: incremental

  silver:
    +schema: SILVER
    +materialized: view

  gold:
    +schema: GOLD
    +materialized: view


snapshots:
  +schema: SILVER

seeds:
  +schema: SILVER






